//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiteRight.Resources.Resources.Onboard {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Onboard {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Onboard() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BiteRight.Resources.Resources.Onboard.Onboard", typeof(Onboard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string username_in_use {
            get {
                return ResourceManager.GetString("username_in_use", resourceCulture);
            }
        }
        
        public static string email_in_use {
            get {
                return ResourceManager.GetString("email_in_use", resourceCulture);
            }
        }
        
        public static string username_empty {
            get {
                return ResourceManager.GetString("username_empty", resourceCulture);
            }
        }
        
        public static string username_characters_not_valid {
            get {
                return ResourceManager.GetString("username_characters_not_valid", resourceCulture);
            }
        }
        
        public static string username_length_not_valid {
            get {
                return ResourceManager.GetString("username_length_not_valid", resourceCulture);
            }
        }
        
        public static string email_not_valid {
            get {
                return ResourceManager.GetString("email_not_valid", resourceCulture);
            }
        }
        
        public static string user_already_exists {
            get {
                return ResourceManager.GetString("user_already_exists", resourceCulture);
            }
        }
    }
}
