// <auto-generated />
using System;
using BiteRight.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BiteRight.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231225132018_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BiteRight.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", "category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8c78317-70ac-4051-805e-ece2bb37656f")
                        },
                        new
                        {
                            Id = new Guid("1fd7ed59-9e34-40ab-a03d-6282b5d9fd86")
                        },
                        new
                        {
                            Id = new Guid("349774c7-3249-4245-a1e2-5b70c5725bbf")
                        },
                        new
                        {
                            Id = new Guid("5e40ba93-d28c-4cf3-9e75-379040a18e52")
                        },
                        new
                        {
                            Id = new Guid("17c56168-c9ec-4ffb-a074-495a02ab0359")
                        });
                });

            modelBuilder.Entity("BiteRight.Domain.Categories.CategoryTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_category_translations");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_category_translations_category_id");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_category_translations_language_id");

                    b.ToTable("category_translations", "category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("38097234-329c-4372-a54f-13e6c41004fa"),
                            CategoryId = new Guid("e8c78317-70ac-4051-805e-ece2bb37656f"),
                            LanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a"),
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = new Guid("96a2257a-f4c4-4c47-9b5b-50a7be92c5da"),
                            CategoryId = new Guid("e8c78317-70ac-4051-805e-ece2bb37656f"),
                            LanguageId = new Guid("24d48691-7325-4703-b69f-8db933a6736d"),
                            Name = "Nabiał"
                        },
                        new
                        {
                            Id = new Guid("c089f04f-fdfe-48e1-87b7-ff8028ecb67f"),
                            CategoryId = new Guid("e8c78317-70ac-4051-805e-ece2bb37656f"),
                            LanguageId = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3"),
                            Name = "Milchprodukte"
                        },
                        new
                        {
                            Id = new Guid("73127f14-9fe8-4dd7-b4bf-e11d98c6e505"),
                            CategoryId = new Guid("1fd7ed59-9e34-40ab-a03d-6282b5d9fd86"),
                            LanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a"),
                            Name = "Fruit"
                        },
                        new
                        {
                            Id = new Guid("af5072c0-7282-481f-a623-f4e00feb2bf8"),
                            CategoryId = new Guid("1fd7ed59-9e34-40ab-a03d-6282b5d9fd86"),
                            LanguageId = new Guid("24d48691-7325-4703-b69f-8db933a6736d"),
                            Name = "Owoce"
                        },
                        new
                        {
                            Id = new Guid("532bfdc2-bd1a-40eb-8723-65ae4e76f242"),
                            CategoryId = new Guid("1fd7ed59-9e34-40ab-a03d-6282b5d9fd86"),
                            LanguageId = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3"),
                            Name = "Obst"
                        },
                        new
                        {
                            Id = new Guid("7ec1928d-1517-4ef1-a24f-cf20322f34a5"),
                            CategoryId = new Guid("349774c7-3249-4245-a1e2-5b70c5725bbf"),
                            LanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a"),
                            Name = "Vegetable"
                        },
                        new
                        {
                            Id = new Guid("b9e41376-b606-42d3-b2af-8373c1905b87"),
                            CategoryId = new Guid("349774c7-3249-4245-a1e2-5b70c5725bbf"),
                            LanguageId = new Guid("24d48691-7325-4703-b69f-8db933a6736d"),
                            Name = "Warzywa"
                        },
                        new
                        {
                            Id = new Guid("115fbaa7-0bcc-4d41-b1f1-43fe1cdb28f9"),
                            CategoryId = new Guid("349774c7-3249-4245-a1e2-5b70c5725bbf"),
                            LanguageId = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3"),
                            Name = "Gemüse"
                        },
                        new
                        {
                            Id = new Guid("a2c2d7cb-e684-4c71-80e0-07aa1db6d5ba"),
                            CategoryId = new Guid("5e40ba93-d28c-4cf3-9e75-379040a18e52"),
                            LanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a"),
                            Name = "Meat"
                        },
                        new
                        {
                            Id = new Guid("f7f1c6e7-012f-449c-95a3-79459f9331fb"),
                            CategoryId = new Guid("5e40ba93-d28c-4cf3-9e75-379040a18e52"),
                            LanguageId = new Guid("24d48691-7325-4703-b69f-8db933a6736d"),
                            Name = "Mięso"
                        },
                        new
                        {
                            Id = new Guid("04b42267-4c3e-4ac1-9972-90112ba7c952"),
                            CategoryId = new Guid("5e40ba93-d28c-4cf3-9e75-379040a18e52"),
                            LanguageId = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3"),
                            Name = "Fleisch"
                        },
                        new
                        {
                            Id = new Guid("bd8fefc6-70ce-4562-9730-274c589ca72b"),
                            CategoryId = new Guid("17c56168-c9ec-4ffb-a074-495a02ab0359"),
                            LanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a"),
                            Name = "Fish"
                        },
                        new
                        {
                            Id = new Guid("15e9f981-3a22-4bb2-96f7-5cc559567794"),
                            CategoryId = new Guid("17c56168-c9ec-4ffb-a074-495a02ab0359"),
                            LanguageId = new Guid("24d48691-7325-4703-b69f-8db933a6736d"),
                            Name = "Ryby"
                        },
                        new
                        {
                            Id = new Guid("c605cdf4-8b17-4cf0-950a-5a9bee434145"),
                            CategoryId = new Guid("17c56168-c9ec-4ffb-a074-495a02ab0359"),
                            LanguageId = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3"),
                            Name = "Fisch"
                        });
                });

            modelBuilder.Entity("BiteRight.Domain.Countries.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alpha2Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alpha2code");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("english_name");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("native_name");

                    b.Property<Guid>("OfficialLanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("official_language_id");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.ToTable("countries", "country");

                    b.HasData(
                        new
                        {
                            Id = new Guid("35d08361-f753-4db9-b88e-11c400d53eb7"),
                            Alpha2Code = "pl",
                            EnglishName = "Poland",
                            NativeName = "Polska",
                            OfficialLanguageId = new Guid("24d48691-7325-4703-b69f-8db933a6736d")
                        },
                        new
                        {
                            Id = new Guid("f3e4c5cb-229c-4b2d-90dc-f83cb4a45f75"),
                            Alpha2Code = "en",
                            EnglishName = "England",
                            NativeName = "England",
                            OfficialLanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a")
                        },
                        new
                        {
                            Id = new Guid("1352de6e-c0bf-48c6-b703-fae0b254d642"),
                            Alpha2Code = "de",
                            EnglishName = "Germany",
                            NativeName = "Deutschland",
                            OfficialLanguageId = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3")
                        },
                        new
                        {
                            Id = new Guid("12e2937f-f04d-4150-a7ae-5ab1176a95d8"),
                            Alpha2Code = "us",
                            EnglishName = "United States of America",
                            NativeName = "United States of America",
                            OfficialLanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a")
                        });
                });

            modelBuilder.Entity("BiteRight.Domain.Languages.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_languages");

                    b.ToTable("languages", "language");

                    b.HasData(
                        new
                        {
                            Id = new Guid("24d48691-7325-4703-b69f-8db933a6736d"),
                            Code = "pl",
                            Name = "Polski"
                        },
                        new
                        {
                            Id = new Guid("454faf9a-644c-445c-89e3-b57203957c1a"),
                            Code = "en",
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3"),
                            Code = "de",
                            Name = "Deutsch"
                        });
                });

            modelBuilder.Entity("BiteRight.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("IdentityId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_identity_id");

                    b.ToTable("users", "user");
                });

            modelBuilder.Entity("BiteRight.Domain.Categories.CategoryTranslation", b =>
                {
                    b.HasOne("BiteRight.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_translations_categories_category_id");

                    b.HasOne("BiteRight.Domain.Languages.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_translations_languages_language_temp_id1");
                });
#pragma warning restore 612, 618
        }
    }
}
