// <auto-generated />
using System;
using BiteRight.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BiteRight.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240301132120_More_Currencies")]
    partial class More_Currencies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BiteRight.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("PhotoId")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_photo_id");

                    b.ToTable("categories", "category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c82e0550-26cf-410d-8cec-5cf62bada757"),
                            IsDefault = true
                        },
                        new
                        {
                            Id = new Guid("e8c78317-70ac-4051-805e-ece2bb37656f"),
                            IsDefault = false,
                            PhotoId = new Guid("98eb4dc2-11b5-440b-bfc1-742fda8279b7")
                        },
                        new
                        {
                            Id = new Guid("1fd7ed59-9e34-40ab-a03d-6282b5d9fd86"),
                            IsDefault = false,
                            PhotoId = new Guid("5e4d81da-841b-493a-a47b-9f69791e1063")
                        },
                        new
                        {
                            Id = new Guid("349774c7-3249-4245-a1e2-5b70c5725bbf"),
                            IsDefault = false,
                            PhotoId = new Guid("2eaee2ac-3ebf-49f2-807b-1b0509f528ba")
                        },
                        new
                        {
                            Id = new Guid("5e40ba93-d28c-4cf3-9e75-379040a18e52"),
                            IsDefault = false,
                            PhotoId = new Guid("4d4c96bc-6990-4b94-982e-d5e7860019a1")
                        },
                        new
                        {
                            Id = new Guid("17c56168-c9ec-4ffb-a074-495a02ab0359"),
                            IsDefault = false,
                            PhotoId = new Guid("2bfd1c0c-8882-44fa-b73d-8588ad8ec50b")
                        },
                        new
                        {
                            Id = new Guid("7289cbc9-8249-4fc1-b2d3-bac90ad32595"),
                            IsDefault = false,
                            PhotoId = new Guid("a186163e-0551-4968-8706-543c470db6db")
                        },
                        new
                        {
                            Id = new Guid("e86caf03-ea3b-49ab-b499-68e387919fb6"),
                            IsDefault = false,
                            PhotoId = new Guid("4ceca44a-b13b-456a-9315-46b506076af4")
                        },
                        new
                        {
                            Id = new Guid("bf69966b-0cbc-4f5d-9388-c05926775cbf"),
                            IsDefault = false,
                            PhotoId = new Guid("a2f14ba8-b9be-40cd-9be0-b3c587be2fc3")
                        },
                        new
                        {
                            Id = new Guid("854cd0f7-4cea-4ad3-b68c-a3e84948cd3e"),
                            IsDefault = false,
                            PhotoId = new Guid("02f43b77-f3fc-4d97-a53c-a45fac195171")
                        });
                });

            modelBuilder.Entity("BiteRight.Domain.Categories.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_photos");

                    b.ToTable("photos", "category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4aa9576b-8f3d-4a09-a66e-caa3fddfb4fb"),
                            Name = "default.webp"
                        },
                        new
                        {
                            Id = new Guid("98eb4dc2-11b5-440b-bfc1-742fda8279b7"),
                            Name = "dairy.webp"
                        },
                        new
                        {
                            Id = new Guid("5e4d81da-841b-493a-a47b-9f69791e1063"),
                            Name = "fruit.webp"
                        },
                        new
                        {
                            Id = new Guid("2eaee2ac-3ebf-49f2-807b-1b0509f528ba"),
                            Name = "vegetable.webp"
                        },
                        new
                        {
                            Id = new Guid("4d4c96bc-6990-4b94-982e-d5e7860019a1"),
                            Name = "meat.webp"
                        },
                        new
                        {
                            Id = new Guid("2bfd1c0c-8882-44fa-b73d-8588ad8ec50b"),
                            Name = "fish.webp"
                        },
                        new
                        {
                            Id = new Guid("a186163e-0551-4968-8706-543c470db6db"),
                            Name = "beverage.webp"
                        },
                        new
                        {
                            Id = new Guid("4ceca44a-b13b-456a-9315-46b506076af4"),
                            Name = "snack.webp"
                        },
                        new
                        {
                            Id = new Guid("a2f14ba8-b9be-40cd-9be0-b3c587be2fc3"),
                            Name = "wheat.webp"
                        },
                        new
                        {
                            Id = new Guid("02f43b77-f3fc-4d97-a53c-a45fac195171"),
                            Name = "dish.webp"
                        });
                });

            modelBuilder.Entity("BiteRight.Domain.Categories.Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_category_translations");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_category_translations_category_id");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_category_translations_language_id");

                    b.ToTable("category_translations", "category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7b5e10f-0719-4731-831a-ffe0a1a1ed07"),
                            CategoryId = new Guid("c82e0550-26cf-410d-8cec-5cf62bada757"),
                            LanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a"),
                            Name = "None"
                        },
                        new
                        {
                            Id = new Guid("abed62c9-41b4-462f-866b-06d714dec958"),
                            CategoryId = new Guid("c82e0550-26cf-410d-8cec-5cf62bada757"),
                            LanguageId = new Guid("24d48691-7325-4703-b69f-8db933a6736d"),
                            Name = "Brak"
                        },
                        new
                        {
                            Id = new Guid("206a3c95-fb6d-4127-a37b-9f328c021021"),
                            CategoryId = new Guid("c82e0550-26cf-410d-8cec-5cf62bada757"),
                            LanguageId = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3"),
                            Name = "Keine"
                        },
                        new
                        {
                            Id = new Guid("38097234-329c-4372-a54f-13e6c41004fa"),
                            CategoryId = new Guid("e8c78317-70ac-4051-805e-ece2bb37656f"),
                            LanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a"),
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = new Guid("96a2257a-f4c4-4c47-9b5b-50a7be92c5da"),
                            CategoryId = new Guid("e8c78317-70ac-4051-805e-ece2bb37656f"),
                            LanguageId = new Guid("24d48691-7325-4703-b69f-8db933a6736d"),
                            Name = "Nabiał"
                        },
                        new
                        {
                            Id = new Guid("c089f04f-fdfe-48e1-87b7-ff8028ecb67f"),
                            CategoryId = new Guid("e8c78317-70ac-4051-805e-ece2bb37656f"),
                            LanguageId = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3"),
                            Name = "Milchprodukte"
                        },
                        new
                        {
                            Id = new Guid("73127f14-9fe8-4dd7-b4bf-e11d98c6e505"),
                            CategoryId = new Guid("1fd7ed59-9e34-40ab-a03d-6282b5d9fd86"),
                            LanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a"),
                            Name = "Fruit"
                        },
                        new
                        {
                            Id = new Guid("af5072c0-7282-481f-a623-f4e00feb2bf8"),
                            CategoryId = new Guid("1fd7ed59-9e34-40ab-a03d-6282b5d9fd86"),
                            LanguageId = new Guid("24d48691-7325-4703-b69f-8db933a6736d"),
                            Name = "Owoce"
                        },
                        new
                        {
                            Id = new Guid("532bfdc2-bd1a-40eb-8723-65ae4e76f242"),
                            CategoryId = new Guid("1fd7ed59-9e34-40ab-a03d-6282b5d9fd86"),
                            LanguageId = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3"),
                            Name = "Obst"
                        },
                        new
                        {
                            Id = new Guid("7ec1928d-1517-4ef1-a24f-cf20322f34a5"),
                            CategoryId = new Guid("349774c7-3249-4245-a1e2-5b70c5725bbf"),
                            LanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a"),
                            Name = "Vegetable"
                        },
                        new
                        {
                            Id = new Guid("b9e41376-b606-42d3-b2af-8373c1905b87"),
                            CategoryId = new Guid("349774c7-3249-4245-a1e2-5b70c5725bbf"),
                            LanguageId = new Guid("24d48691-7325-4703-b69f-8db933a6736d"),
                            Name = "Warzywa"
                        },
                        new
                        {
                            Id = new Guid("115fbaa7-0bcc-4d41-b1f1-43fe1cdb28f9"),
                            CategoryId = new Guid("349774c7-3249-4245-a1e2-5b70c5725bbf"),
                            LanguageId = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3"),
                            Name = "Gemüse"
                        },
                        new
                        {
                            Id = new Guid("a2c2d7cb-e684-4c71-80e0-07aa1db6d5ba"),
                            CategoryId = new Guid("5e40ba93-d28c-4cf3-9e75-379040a18e52"),
                            LanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a"),
                            Name = "Meat"
                        },
                        new
                        {
                            Id = new Guid("f7f1c6e7-012f-449c-95a3-79459f9331fb"),
                            CategoryId = new Guid("5e40ba93-d28c-4cf3-9e75-379040a18e52"),
                            LanguageId = new Guid("24d48691-7325-4703-b69f-8db933a6736d"),
                            Name = "Mięso"
                        },
                        new
                        {
                            Id = new Guid("04b42267-4c3e-4ac1-9972-90112ba7c952"),
                            CategoryId = new Guid("5e40ba93-d28c-4cf3-9e75-379040a18e52"),
                            LanguageId = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3"),
                            Name = "Fleisch"
                        },
                        new
                        {
                            Id = new Guid("bd8fefc6-70ce-4562-9730-274c589ca72b"),
                            CategoryId = new Guid("17c56168-c9ec-4ffb-a074-495a02ab0359"),
                            LanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a"),
                            Name = "Fish"
                        },
                        new
                        {
                            Id = new Guid("15e9f981-3a22-4bb2-96f7-5cc559567794"),
                            CategoryId = new Guid("17c56168-c9ec-4ffb-a074-495a02ab0359"),
                            LanguageId = new Guid("24d48691-7325-4703-b69f-8db933a6736d"),
                            Name = "Ryby"
                        },
                        new
                        {
                            Id = new Guid("c605cdf4-8b17-4cf0-950a-5a9bee434145"),
                            CategoryId = new Guid("17c56168-c9ec-4ffb-a074-495a02ab0359"),
                            LanguageId = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3"),
                            Name = "Fisch"
                        },
                        new
                        {
                            Id = new Guid("2e24ca76-c17c-4a80-874b-98a33b825567"),
                            CategoryId = new Guid("7289cbc9-8249-4fc1-b2d3-bac90ad32595"),
                            LanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a"),
                            Name = "Beverage"
                        },
                        new
                        {
                            Id = new Guid("329f0e4b-b364-41f9-ad75-804d796bcc74"),
                            CategoryId = new Guid("7289cbc9-8249-4fc1-b2d3-bac90ad32595"),
                            LanguageId = new Guid("24d48691-7325-4703-b69f-8db933a6736d"),
                            Name = "Napój"
                        },
                        new
                        {
                            Id = new Guid("62334e0c-acba-47c7-a98a-9a606fed9084"),
                            CategoryId = new Guid("7289cbc9-8249-4fc1-b2d3-bac90ad32595"),
                            LanguageId = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3"),
                            Name = "Getränk"
                        },
                        new
                        {
                            Id = new Guid("718badd8-b2c2-4d4d-bd2b-2959f4949080"),
                            CategoryId = new Guid("e86caf03-ea3b-49ab-b499-68e387919fb6"),
                            LanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a"),
                            Name = "Snack"
                        },
                        new
                        {
                            Id = new Guid("4daa9144-5f43-401b-8622-3ac7b1cc14ff"),
                            CategoryId = new Guid("e86caf03-ea3b-49ab-b499-68e387919fb6"),
                            LanguageId = new Guid("24d48691-7325-4703-b69f-8db933a6736d"),
                            Name = "Przekąska"
                        },
                        new
                        {
                            Id = new Guid("b151fa8f-6361-40e5-99da-1ad19108af04"),
                            CategoryId = new Guid("e86caf03-ea3b-49ab-b499-68e387919fb6"),
                            LanguageId = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3"),
                            Name = "Snack"
                        },
                        new
                        {
                            Id = new Guid("f121fb7f-ce98-4348-9e1d-9353c1d82df9"),
                            CategoryId = new Guid("bf69966b-0cbc-4f5d-9388-c05926775cbf"),
                            LanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a"),
                            Name = "Wheat"
                        },
                        new
                        {
                            Id = new Guid("432866df-ef78-4eae-8cc3-0e2ab2efb801"),
                            CategoryId = new Guid("bf69966b-0cbc-4f5d-9388-c05926775cbf"),
                            LanguageId = new Guid("24d48691-7325-4703-b69f-8db933a6736d"),
                            Name = "Pszenica"
                        },
                        new
                        {
                            Id = new Guid("24ba2bc6-8bc6-4a11-96dc-0de686de742f"),
                            CategoryId = new Guid("bf69966b-0cbc-4f5d-9388-c05926775cbf"),
                            LanguageId = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3"),
                            Name = "Weizen"
                        },
                        new
                        {
                            Id = new Guid("bfb53dfb-cb0f-4ba4-9ec6-4052b4e3ae98"),
                            CategoryId = new Guid("854cd0f7-4cea-4ad3-b68c-a3e84948cd3e"),
                            LanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a"),
                            Name = "Dish"
                        },
                        new
                        {
                            Id = new Guid("3c2f5d1e-16f6-4109-b42f-ec4f1731ea62"),
                            CategoryId = new Guid("854cd0f7-4cea-4ad3-b68c-a3e84948cd3e"),
                            LanguageId = new Guid("24d48691-7325-4703-b69f-8db933a6736d"),
                            Name = "Danie"
                        },
                        new
                        {
                            Id = new Guid("6729644a-7232-4483-bd90-7839732f6c7b"),
                            CategoryId = new Guid("854cd0f7-4cea-4ad3-b68c-a3e84948cd3e"),
                            LanguageId = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3"),
                            Name = "Gericht"
                        });
                });

            modelBuilder.Entity("BiteRight.Domain.Countries.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alpha2Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alpha2code");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("english_name");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("native_name");

                    b.Property<Guid>("OfficialLanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("official_language_id");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_countries_currency_id");

                    b.HasIndex("OfficialLanguageId")
                        .HasDatabaseName("ix_countries_official_language_id");

                    b.ToTable("countries", "country");

                    b.HasData(
                        new
                        {
                            Id = new Guid("35d08361-f753-4db9-b88e-11c400d53eb7"),
                            Alpha2Code = "PL",
                            CurrencyId = new Guid("3b56a6de-3b41-4b10-934f-469ca12f4fe3"),
                            EnglishName = "Poland",
                            NativeName = "Polska",
                            OfficialLanguageId = new Guid("24d48691-7325-4703-b69f-8db933a6736d")
                        },
                        new
                        {
                            Id = new Guid("f3e4c5cb-229c-4b2d-90dc-f83cb4a45f75"),
                            Alpha2Code = "EN",
                            CurrencyId = new Guid("53dffab5-429d-4626-b1d9-f568119e069a"),
                            EnglishName = "England",
                            NativeName = "England",
                            OfficialLanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a")
                        },
                        new
                        {
                            Id = new Guid("1352de6e-c0bf-48c6-b703-fae0b254d642"),
                            Alpha2Code = "DE",
                            CurrencyId = new Guid("8b0a0882-3eb5-495a-a646-06d7e0e9fe99"),
                            EnglishName = "Germany",
                            NativeName = "Deutschland",
                            OfficialLanguageId = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3")
                        },
                        new
                        {
                            Id = new Guid("12e2937f-f04d-4150-a7ae-5ab1176a95d8"),
                            Alpha2Code = "US",
                            CurrencyId = new Guid("e862f33f-a04a-4b4e-a4bb-9542b1db3eeb"),
                            EnglishName = "United States of America",
                            NativeName = "United States of America",
                            OfficialLanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a")
                        });
                });

            modelBuilder.Entity("BiteRight.Domain.Currencies.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ISO4217Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("iso4217code");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_currencies");

                    b.ToTable("currencies", "currency");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3b56a6de-3b41-4b10-934f-469ca12f4fe3"),
                            ISO4217Code = "PLN",
                            IsDefault = false,
                            Name = "Polski złoty",
                            Symbol = "zł"
                        },
                        new
                        {
                            Id = new Guid("53dffab5-429d-4626-b1d9-f568119e069a"),
                            ISO4217Code = "GBP",
                            IsDefault = false,
                            Name = "Pound sterling",
                            Symbol = "£"
                        },
                        new
                        {
                            Id = new Guid("8b0a0882-3eb5-495a-a646-06d7e0e9fe99"),
                            ISO4217Code = "EUR",
                            IsDefault = false,
                            Name = "Euro",
                            Symbol = "€"
                        },
                        new
                        {
                            Id = new Guid("e862f33f-a04a-4b4e-a4bb-9542b1db3eeb"),
                            ISO4217Code = "USD",
                            IsDefault = true,
                            Name = "United States dollar",
                            Symbol = "US$"
                        },
                        new
                        {
                            Id = new Guid("776c1e32-3a9d-4e91-869f-81e89bc17465"),
                            ISO4217Code = "JPY",
                            IsDefault = false,
                            Name = "Japanese yen",
                            Symbol = "¥"
                        },
                        new
                        {
                            Id = new Guid("5efc5c7c-872d-4559-a3f3-ecc53f8ae59e"),
                            ISO4217Code = "AUD",
                            IsDefault = false,
                            Name = "Australian dollar",
                            Symbol = "A$"
                        },
                        new
                        {
                            Id = new Guid("f7e66c98-4dc8-43d8-b77b-8f9848a3888f"),
                            ISO4217Code = "CAD",
                            IsDefault = false,
                            Name = "Canadian dollar",
                            Symbol = "C$"
                        },
                        new
                        {
                            Id = new Guid("a418ccb9-82aa-4e69-963b-4736ff1e815a"),
                            ISO4217Code = "CHF",
                            IsDefault = false,
                            Name = "Swiss franc",
                            Symbol = "Fr"
                        },
                        new
                        {
                            Id = new Guid("9490768d-a205-4dcc-bb66-6a007f661b98"),
                            ISO4217Code = "CNY",
                            IsDefault = false,
                            Name = "Chinese yuan",
                            Symbol = "¥"
                        },
                        new
                        {
                            Id = new Guid("9c32a5f5-dc05-4e83-ab12-d26bdd8d0663"),
                            ISO4217Code = "SEK",
                            IsDefault = false,
                            Name = "Swedish krona",
                            Symbol = "kr"
                        },
                        new
                        {
                            Id = new Guid("2bc7bbbc-881b-4460-a099-1d082d11b78b"),
                            ISO4217Code = "NZD",
                            IsDefault = false,
                            Name = "New Zealand dollar",
                            Symbol = "NZ$"
                        },
                        new
                        {
                            Id = new Guid("06fc7d4a-ac95-40e9-a685-0434fda14085"),
                            ISO4217Code = "MXN",
                            IsDefault = false,
                            Name = "Mexican peso",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = new Guid("dd1e997a-bef8-4f62-86ea-6f45bedcccb0"),
                            ISO4217Code = "NOK",
                            IsDefault = false,
                            Name = "Norwegian krone",
                            Symbol = "kr"
                        },
                        new
                        {
                            Id = new Guid("d9b9b44c-1731-4496-8aec-1eb6f32689f0"),
                            ISO4217Code = "SGD",
                            IsDefault = false,
                            Name = "Singapore dollar",
                            Symbol = "S$"
                        },
                        new
                        {
                            Id = new Guid("d502fd4e-77cc-4749-b8b0-cca05f6c7d1c"),
                            ISO4217Code = "HKD",
                            IsDefault = false,
                            Name = "Hong Kong dollar",
                            Symbol = "HK$"
                        },
                        new
                        {
                            Id = new Guid("a353e300-89d7-47b0-9c55-f4c73ad12d98"),
                            ISO4217Code = "KRW",
                            IsDefault = false,
                            Name = "South Korean won",
                            Symbol = "₩"
                        },
                        new
                        {
                            Id = new Guid("f1b638fd-f37f-47c0-943e-a35f44edc2cc"),
                            ISO4217Code = "TRY",
                            IsDefault = false,
                            Name = "Turkish lira",
                            Symbol = "₺"
                        },
                        new
                        {
                            Id = new Guid("9d2c8e61-f2be-43af-8939-8a0700ea7bda"),
                            ISO4217Code = "INR",
                            IsDefault = false,
                            Name = "Indian rupee",
                            Symbol = "₹"
                        },
                        new
                        {
                            Id = new Guid("0cf996fa-3f23-4209-9bad-367d21a1c79a"),
                            ISO4217Code = "BRL",
                            IsDefault = false,
                            Name = "Brazilian real",
                            Symbol = "R$"
                        });
                });

            modelBuilder.Entity("BiteRight.Domain.Languages.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("english_name");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("native_name");

                    b.HasKey("Id")
                        .HasName("pk_languages");

                    b.ToTable("languages", "language");

                    b.HasData(
                        new
                        {
                            Id = new Guid("24d48691-7325-4703-b69f-8db933a6736d"),
                            Code = "pl",
                            EnglishName = "Polish",
                            NativeName = "Polski"
                        },
                        new
                        {
                            Id = new Guid("454faf9a-644c-445c-89e3-b57203957c1a"),
                            Code = "en",
                            EnglishName = "English",
                            NativeName = "English"
                        },
                        new
                        {
                            Id = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3"),
                            Code = "de",
                            EnglishName = "German",
                            NativeName = "Deutsch"
                        });
                });

            modelBuilder.Entity("BiteRight.Domain.Products.Amount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("CurrentValue")
                        .HasColumnType("double precision")
                        .HasColumnName("current_value");

                    b.Property<double>("MaxValue")
                        .HasColumnType("double precision")
                        .HasColumnName("max_value");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_amounts");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_amounts_product_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_amounts_unit_id");

                    b.ToTable("amounts", "product");
                });

            modelBuilder.Entity("BiteRight.Domain.Products.Price", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_prices");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_prices_currency_id");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_prices_product_id");

                    b.ToTable("prices", "product");
                });

            modelBuilder.Entity("BiteRight.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_date_time");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_products_created_by_id");

                    b.ToTable("products", "product");
                });

            modelBuilder.Entity("BiteRight.Domain.Units.Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("abbreviation");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_unit_translations");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_unit_translations_language_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_unit_translations_unit_id");

                    b.ToTable("unit_translations", "unit");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d91f5a31-458e-4d08-bfee-1812183ea35d"),
                            Abbreviation = "L",
                            LanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a"),
                            Name = "Liter",
                            UnitId = new Guid("b6d4d4dd-c035-4047-b8ee-48937cb1f368")
                        },
                        new
                        {
                            Id = new Guid("ca5c1bac-a53d-44bf-9cdf-2cd165047f7b"),
                            Abbreviation = "L",
                            LanguageId = new Guid("24d48691-7325-4703-b69f-8db933a6736d"),
                            Name = "Litr",
                            UnitId = new Guid("b6d4d4dd-c035-4047-b8ee-48937cb1f368")
                        },
                        new
                        {
                            Id = new Guid("ce4f6636-140c-48f7-a2f4-3148045ca0e5"),
                            Abbreviation = "L",
                            LanguageId = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3"),
                            Name = "Liter",
                            UnitId = new Guid("b6d4d4dd-c035-4047-b8ee-48937cb1f368")
                        },
                        new
                        {
                            Id = new Guid("712cd66c-87ac-4af4-bc07-2d42db04e8b3"),
                            Abbreviation = "kg",
                            LanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a"),
                            Name = "Kilogram",
                            UnitId = new Guid("cde52e6c-5d9d-4876-978a-bf67c02cc8be")
                        },
                        new
                        {
                            Id = new Guid("e45767ee-c69c-4c34-9729-ffa396306017"),
                            Abbreviation = "kg",
                            LanguageId = new Guid("24d48691-7325-4703-b69f-8db933a6736d"),
                            Name = "Kilogram",
                            UnitId = new Guid("cde52e6c-5d9d-4876-978a-bf67c02cc8be")
                        },
                        new
                        {
                            Id = new Guid("368fb52e-06d7-4b33-aceb-c7edfdf865ad"),
                            Abbreviation = "kg",
                            LanguageId = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3"),
                            Name = "Kilogramm",
                            UnitId = new Guid("cde52e6c-5d9d-4876-978a-bf67c02cc8be")
                        },
                        new
                        {
                            Id = new Guid("ca64ba08-93bb-432d-afc2-869f6c543922"),
                            Abbreviation = "g",
                            LanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a"),
                            Name = "Gram",
                            UnitId = new Guid("84770558-3345-4d05-9814-21c61fbdbb09")
                        },
                        new
                        {
                            Id = new Guid("0164a42a-a4b7-4e1f-8db8-8158b4605dbc"),
                            Abbreviation = "g",
                            LanguageId = new Guid("24d48691-7325-4703-b69f-8db933a6736d"),
                            Name = "Gram",
                            UnitId = new Guid("84770558-3345-4d05-9814-21c61fbdbb09")
                        },
                        new
                        {
                            Id = new Guid("b6101a50-6f20-42cf-b58d-1a69d77ffdfc"),
                            Abbreviation = "g",
                            LanguageId = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3"),
                            Name = "Gramm",
                            UnitId = new Guid("84770558-3345-4d05-9814-21c61fbdbb09")
                        },
                        new
                        {
                            Id = new Guid("3bf5d07a-6004-4f50-9bc4-59e8831f5e90"),
                            Abbreviation = "ml",
                            LanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a"),
                            Name = "Milliliter",
                            UnitId = new Guid("f13143db-0380-4b90-8b8d-aad8c9ea7d48")
                        },
                        new
                        {
                            Id = new Guid("67cefc87-b43a-4262-9d16-9e12aac5db5e"),
                            Abbreviation = "ml",
                            LanguageId = new Guid("24d48691-7325-4703-b69f-8db933a6736d"),
                            Name = "Mililitr",
                            UnitId = new Guid("f13143db-0380-4b90-8b8d-aad8c9ea7d48")
                        },
                        new
                        {
                            Id = new Guid("dc8020fa-c5c1-4e88-8658-752e5a922c3d"),
                            Abbreviation = "ml",
                            LanguageId = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3"),
                            Name = "Milliliter",
                            UnitId = new Guid("f13143db-0380-4b90-8b8d-aad8c9ea7d48")
                        },
                        new
                        {
                            Id = new Guid("c9194190-521f-40ba-836f-6a8daccb418e"),
                            Abbreviation = "pc",
                            LanguageId = new Guid("454faf9a-644c-445c-89e3-b57203957c1a"),
                            Name = "Piece",
                            UnitId = new Guid("f8920b2a-d1ee-4351-a708-4b82584257f1")
                        },
                        new
                        {
                            Id = new Guid("256783e0-d6ba-4a6f-b0cc-52e3b908820c"),
                            Abbreviation = "szt",
                            LanguageId = new Guid("24d48691-7325-4703-b69f-8db933a6736d"),
                            Name = "Sztuka",
                            UnitId = new Guid("f8920b2a-d1ee-4351-a708-4b82584257f1")
                        },
                        new
                        {
                            Id = new Guid("831090a9-1736-4264-93fb-449aa3d3d02d"),
                            Abbreviation = "st",
                            LanguageId = new Guid("c1dd0a3b-70d3-4aa1-b53e-4c08a03b57c3"),
                            Name = "Stück",
                            UnitId = new Guid("f8920b2a-d1ee-4351-a708-4b82584257f1")
                        });
                });

            modelBuilder.Entity("BiteRight.Domain.Units.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("UnitSystem")
                        .HasColumnType("integer")
                        .HasColumnName("unit_system");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.ToTable("units", "unit");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b6d4d4dd-c035-4047-b8ee-48937cb1f368"),
                            UnitSystem = 1
                        },
                        new
                        {
                            Id = new Guid("cde52e6c-5d9d-4876-978a-bf67c02cc8be"),
                            UnitSystem = 1
                        },
                        new
                        {
                            Id = new Guid("84770558-3345-4d05-9814-21c61fbdbb09"),
                            UnitSystem = 1
                        },
                        new
                        {
                            Id = new Guid("f13143db-0380-4b90-8b8d-aad8c9ea7d48"),
                            UnitSystem = 1
                        },
                        new
                        {
                            Id = new Guid("f8920b2a-d1ee-4351-a708-4b82584257f1"),
                            UnitSystem = 3
                        });
                });

            modelBuilder.Entity("BiteRight.Domain.Users.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_profiles_currency_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_profiles_user_id");

                    b.ToTable("profiles", "user");
                });

            modelBuilder.Entity("BiteRight.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("IdentityId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_identity_id");

                    b.ToTable("users", "user");
                });

            modelBuilder.Entity("BiteRight.Domain.Categories.Category", b =>
                {
                    b.HasOne("BiteRight.Domain.Categories.Photo", "Photo")
                        .WithOne()
                        .HasForeignKey("BiteRight.Domain.Categories.Category", "PhotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_photos_photo_id");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("BiteRight.Domain.Categories.Translation", b =>
                {
                    b.HasOne("BiteRight.Domain.Categories.Category", "Category")
                        .WithMany("Translations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_translations_categories_category_id");

                    b.HasOne("BiteRight.Domain.Languages.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_translations_languages_language_id");

                    b.Navigation("Category");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("BiteRight.Domain.Countries.Country", b =>
                {
                    b.HasOne("BiteRight.Domain.Currencies.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_countries_currencies_currency_id");

                    b.HasOne("BiteRight.Domain.Languages.Language", "OfficialLanguage")
                        .WithMany()
                        .HasForeignKey("OfficialLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_countries_languages_official_language_id");

                    b.Navigation("Currency");

                    b.Navigation("OfficialLanguage");
                });

            modelBuilder.Entity("BiteRight.Domain.Products.Amount", b =>
                {
                    b.HasOne("BiteRight.Domain.Products.Product", "Product")
                        .WithOne("Amount")
                        .HasForeignKey("BiteRight.Domain.Products.Amount", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_amounts_products_product_id");

                    b.HasOne("BiteRight.Domain.Units.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_amounts_units_unit_id");

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("BiteRight.Domain.Products.Price", b =>
                {
                    b.HasOne("BiteRight.Domain.Currencies.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_prices_currencies_currency_id");

                    b.HasOne("BiteRight.Domain.Products.Product", "Product")
                        .WithOne("Price")
                        .HasForeignKey("BiteRight.Domain.Products.Price", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prices_products_product_id");

                    b.Navigation("Currency");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BiteRight.Domain.Products.Product", b =>
                {
                    b.HasOne("BiteRight.Domain.Categories.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");

                    b.HasOne("BiteRight.Domain.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_users_created_by_id");

                    b.OwnsOne("BiteRight.Domain.Products.DisposedState", "DisposedState", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime?>("DateTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("disposed_state_disposed_date");

                            b1.Property<bool>("Value")
                                .HasColumnType("boolean")
                                .HasColumnName("disposed_state_disposed");

                            b1.HasKey("ProductId");

                            b1.ToTable("products", "product");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_products_products_id");
                        });

                    b.OwnsOne("BiteRight.Domain.Products.ExpirationDate", "ExpirationDate", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer")
                                .HasColumnName("expiration_date_kind");

                            b1.Property<DateOnly?>("Value")
                                .HasColumnType("date")
                                .HasColumnName("expiration_date_value");

                            b1.HasKey("ProductId");

                            b1.ToTable("products", "product");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_products_products_id");
                        });

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");

                    b.Navigation("DisposedState")
                        .IsRequired();

                    b.Navigation("ExpirationDate")
                        .IsRequired();
                });

            modelBuilder.Entity("BiteRight.Domain.Units.Translation", b =>
                {
                    b.HasOne("BiteRight.Domain.Languages.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unit_translations_languages_language_id");

                    b.HasOne("BiteRight.Domain.Units.Unit", "Unit")
                        .WithMany("Translations")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unit_translations_units_unit_id");

                    b.Navigation("Language");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("BiteRight.Domain.Users.Profile", b =>
                {
                    b.HasOne("BiteRight.Domain.Currencies.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_profiles_currencies_currency_id");

                    b.HasOne("BiteRight.Domain.Users.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("BiteRight.Domain.Users.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profiles_users_user_id");

                    b.Navigation("Currency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BiteRight.Domain.Categories.Category", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("BiteRight.Domain.Products.Product", b =>
                {
                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Price");
                });

            modelBuilder.Entity("BiteRight.Domain.Units.Unit", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("BiteRight.Domain.Users.User", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
