[package]
name = "persistence"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7.2", features = ["runtime-tokio-native-tls", "json", "postgres", "chrono"] }
errors = { path = "../errors" }
chrono = "0.4.31"
domain = { path = "../domain" }