//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiteRight.Resources.Resources.Products {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Products {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Products() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BiteRight.Resources.Resources.Products.Products", typeof(Products).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string name_empty {
            get {
                return ResourceManager.GetString("name_empty", resourceCulture);
            }
        }
        
        public static string description_null {
            get {
                return ResourceManager.GetString("description_null", resourceCulture);
            }
        }
        
        public static string price_empty {
            get {
                return ResourceManager.GetString("price_empty", resourceCulture);
            }
        }
        
        public static string name_length_not_valid {
            get {
                return ResourceManager.GetString("name_length_not_valid", resourceCulture);
            }
        }
        
        public static string name_characters_not_valid {
            get {
                return ResourceManager.GetString("name_characters_not_valid", resourceCulture);
            }
        }
        
        public static string description_length_not_valid {
            get {
                return ResourceManager.GetString("description_length_not_valid", resourceCulture);
            }
        }
        
        public static string description_characters_not_valid {
            get {
                return ResourceManager.GetString("description_characters_not_valid", resourceCulture);
            }
        }
        
        public static string price_not_valid {
            get {
                return ResourceManager.GetString("price_not_valid", resourceCulture);
            }
        }
        
        public static string expiration_date_infinite {
            get {
                return ResourceManager.GetString("expiration_date_infinite", resourceCulture);
            }
        }
        
        public static string expiration_date_kind_invalid {
            get {
                return ResourceManager.GetString("expiration_date_kind_invalid", resourceCulture);
            }
        }
        
        public static string sorting_strategy_invalid {
            get {
                return ResourceManager.GetString("sorting_strategy_invalid", resourceCulture);
            }
        }
        
        public static string expiration_date_not_null {
            get {
                return ResourceManager.GetString("expiration_date_not_null", resourceCulture);
            }
        }
        
        public static string expiration_date_empty {
            get {
                return ResourceManager.GetString("expiration_date_empty", resourceCulture);
            }
        }
        
        public static string time_zone_not_found {
            get {
                return ResourceManager.GetString("time_zone_not_found", resourceCulture);
            }
        }
        
        public static string product_id_empty {
            get {
                return ResourceManager.GetString("product_id_empty", resourceCulture);
            }
        }
        
        public static string product_not_found {
            get {
                return ResourceManager.GetString("product_not_found", resourceCulture);
            }
        }
        
        public static string product_already_disposed {
            get {
                return ResourceManager.GetString("product_already_disposed", resourceCulture);
            }
        }
    }
}
